alphasights/ember-graphql-adapter

addon/adapter.js
tests/integration/adapter-test.js

Add queryRecord and cover public API with tests

---

addon/generator.js
tests/integration/adapter-test.js
tests/unit/compiler-test.js
tests/unit/generator-test.js

I've noticed that the output of the generator wasn't returning consistent spacing, so I refactored it a little bit.

Improve generator output with more consistent spacing

---

README.md

add ember observer badge to readme

---

addon/types/argument-set.js
tests/unit/types/argument-set-test.js

because: https://facebook.github.io/graphql/#sec-Non-Null

Don't allow null arguments

---

addon/adapter.js
tests/integration/adapter-test.js

Normalize operation names using normalizeCase

---

addon/serializer.js
tests/helpers/snapshot-double.js
tests/unit/serializer-test.js

Add support for serializing hasMany relationships ids

---

addon/adapter.js

Send whole object representation when updating a record

---

addon/adapter.js
addon/compiler.js
addon/parser.js
tests/integration/adapter-test.js
tests/unit/compiler-test.js
tests/unit/parser-test.js

Make it so that deleteRecord doesn't select fields

---

addon/adapter.js
bower.json
package.json

This PR updates the adapter error handling code to ember-data v2.4.3

Update error handling code

---

addon/parser.js
tests/integration/adapter-test.js

Fixes https://github.com/alphasights/ember-graphql-adapter/issues/43

Stop aliasing relationships with custom names

---

package.json
yarn.lock

chore(package): update ember-data to version 2.12.2

---

package.json
yarn.lock

Update ember-resolver to version 4.1.0

---

.eslintrc.js
package.json
tests/.eslintrc.js
yarn.lock

Update ember-cli to version 2.12.2

---

package.json
yarn.lock

Update ember-cli-babel to version 6.0.0

---

package.json
yarn.lock

Update ember-cli-eslint to version 3.1.0

---

.bowerrc
.eslintrc.js
.travis.yml
bower.json
package.json
tests/dummy/config/targets.js
yarn.lock

Update ember-cli to version 2.13.0

---

package.json
yarn.lock

Update ember-source to version 2.13.2

---

package.json
yarn.lock

Update ember-data to version 2.13.1

---

package.json
yarn.lock

Update ember-cli-htmlbars to version 2.0.1

---

package.json
yarn.lock

Update ember-cli-htmlbars-inline-precompile to version 0.4.3

---

addon/adapter.js

Forgot to handle the rejection as well 🙄

Reject promise when ajax request rejects promise on error
