alphasights/ember-graphql-adapter

addon/adapter.js, addon/compiler.js, addon/parser.js, addon/serializer.js, bower.json, package.json, tests/helpers/model-double.js, tests/helpers/snapshot-double.js, tests/helpers/store-double.js, tests/helpers/store.js, tests/integration/adapter-test.js, tests/unit/compiler-test.js, tests/unit/parser-test.js, tests/unit/serializer-test.js
This PR adds support for both synchronous and asynchronous `hasMany` associations.
Users can now select their own HTTP method for the GraphQL endpoint.
=> Add support for hasMany associations

addon/generator.js, tests/integration/adapter-test.js, tests/unit/generator-test.js
There is a discrepancy in the way that queries are formed with respect to requests for one elements versus a set of elements.
At this time, when the argument is one id, the adapter wraps the id in string tokens, a la `items(id: "1")`. However, when the argument is in array, it does not stringify each individual element, so the request looks like `items(ids: [1,2,3])`. This is an issue because it makes an assumptions that ids will always be integers - this might be the case for a majority of cases in Rails, but it prevents any sort of customization that might appear when particular Models have non-traditional id conventions.
This PR surrounds individual array elements with string tokens to solve the above issue. To do this, it creates a method `wrapArrayInStringTokens`, which surrounds …
=> Stringify Individual Array Elements

addon/adapter.js
Fixes a bug where the error isn't being return in the format Ember is expecting
Paired with @delkopiso
=> Error Handler Fix

addon/parser.js, tests/unit/parser-test.js
By tracking which models/relationships have been processed we can make sure we don't process models and relationships that we've already dealt.
=> Prevent selection set parsing from entering infinite loop

addon/serializer.js, tests/integration/serializer-test.js
The `keyForRelationship` and `keyForAttribute` methods should not care in which direction we are serializing our data. As a result we can simplify them a bit more. Also fixes an incorrect test that prevented this problem from being noticed.
=> Fix `keyForRelationship` method by simplifying it

addon/serializer.js, tests/integration/adapter-test.js
The GraphQL spec defines a string as being enclosed in double quotes. However, if a string attribute were to have a double quoted character sequence within itself, then we would be faced with GraphQL parsing errors. For example,
```
mutation user_update { user: user_update(id: "1", name: "Jeff "The Jeff" Reine-Adelaide") { id name } }
```
The above results in the server thinking that the string value of the `name` argument is `"Jeff "`, and it promptly complains about the succeeding character `T` which it doesn't expect.
=> Escape quotes in strings

addon/serializer.js, tests/integration/serializer-test.js
This PR adds support for custom meta information to be parsed by the graphql adapter. This can enable easy support for things like pagination or other types of metadata :)
=> Support inclusion of meta information

addon/serializer.js, tests/integration/serializer-test.js
Using a GraphQL server that returns a 200 response status for every request, we have to rely on the content of the payload to provide context for how successful the request was. 
Currently, if this request
`query { post(id: "1") { id title body } }`
returns with this payload
```
{
'data': {
'post': null
}
}
```
we should interpret this as a not found ([see JSONAPI spec](http://jsonapi.org/format/#fetching-resources)).
Instead, we end up with an assertion error of this variety:
`Assertion Failed: The root of the result must be the model class name or the plural model class name`
=> Fix error when fetching a resource returns a null object

addon/types/argument-set.js, tests/unit/types/argument-set-test.js
The GraphQL spec now officially includes a Null Value. This is especially useful in a scenario where we need to differentiate between the absence of an argument and an argument that is being unset.
Example:
```
mutation {
user_update(id: "1", address: null) {
id
address
}
}
```
=> Allow null arguments

addon/adapter.js
https://github.com/alphasights/ember-graphql-adapter/pull/27 introduced sending entire snapshots back to the API. However, we cannot keep doing that if we want to properly support the explicit setting/unsetting behavior required by the introduction of the `null` value into the GraphQL spec.
=> Stop sending entire snapshot when saving records

addon/parser.js, tests/unit/parser-test.js
Given a model as such:
```javascript
// app/models/node.js
import DS from 'ember-data';
export default DS.Model.extend({
name: DS.attr('string'),
parent: DS.hasMany('node', { inverse: 'children' }),
children: DS.hasMany('node', { inverse: 'parent' })
});
```
We are generating this query:
```graphql
query node {
node(id: "my_node_id") {
id
name
parents {
id
name
children {
id
name
}
}
}
}
```
This is a side effect of the recursion used to implement the support for
deeply nested synchronous relationships.
Switch to an iterative algorithm for traversing the model tree.
We now get a query like this:
```graphql
query node {
node(id: "my_node_id") {
id
name
parent {
id
name
children {
id
name
}
}
children {
id
name
}
}
}
```
Fixes https://github.com/alphasights/ember-graphql-adapter/issues/75
=> Fix erroneous nesting for reflexive relationships

addon/generator.js, addon/types/argument-set.js, addon/types/selection-set.js, tests/unit/parser-test.js, tests/unit/types/argument-set-test.js, tests/unit/types/argument-test.js, tests/unit/types/field-test.js, tests/unit/types/selection-set-test.js
Instead of extending the native class Array, provide a `toArray()` method which returns a real instance of an Array for the caller to do as they see fit.
=> Stop extending Array

addon/generator.js, tests/unit/generator-test.js
**Problem**: when mutating with embedded records, arrays of objects were not being serialised correctly, appearing as `modelName: "[object Object]"` in the request string. This was due to all array elements being wrapped in string tokens in the `wrapArrayInStringTokens` method in `generator.js`.
**Solution**: for each object in an array, generate arguments for each key-value pair. This allows the building of a string in the form `modelName: [{ key: "value" }]` that can be passed back as part of the request, only wrapping object values in the string tokens instead of the entire object.
=> Generate correct string for object arrays

addon/adapter.js
After https://github.com/alphasights/ember-graphql-adapter/commit/a3e45184185811f52696b578578d1ebe81995c19, we no longer rejected the promise from an ajax request when receiving a response with status 200 but an `errors` key in the response. This caused problems further along when Ember tried interpreting `null` as an actual record.
=> Update adapter ajax function to reject when response contains errors

addon/adapter.js, addon/parser.js, addon/serializer.js, package.json, yarn.lock
We're using ember-inflector incorrectly in two [deprecated](https://github.com/emberjs/ember-inflector/pull/131) ways:
- via `Ember.Inflector`
- via `Ember.String.singularize` and `Ember.String.pluralize`
and `ember-inflector` is not even listed as a dependency.
- Declares `ember-inflector` as an explicit dependency.
- Fixes usage of `singularize` and `pluralize`.
- Fixes usage of `Ember.Inflector` as prescribed in the [ember guides](https://guides.emberjs.com/v2.16.0/models/customizing-adapters/#toc_pluralization-customization)
=> Fix incoherent usage of ember-inflector

addon/adapter.js, addon/generator.js, addon/serializer.js, addon/types/argument-set.js, tests/helpers/owner.js, tests/helpers/store.js, tests/integration/adapter-test.js, tests/integration/serializer-test.js, tests/unit/compiler-test.js, tests/unit/parser-test.js
Used the CLI utility `ember-modules-codemod` to migrate the app as per the instructions on the [ember 2.16 release blog post](https://www.emberjs.com/blog/2017/10/11/ember-2-16-released.html#toc_updating-your-application).
=> Migrate to new ember modules api

addon/generator.js, tests/unit/generator-test.js
```
else if (typeOf(value) === 'object') {
value = this.argumentObjectOpeningToken + this.generateArgumentSet(value) + this.argumentObjectClosingToken;
}
```
When value is an object that is being passing into `generateArgumentSet`, the following error occurs because the method is trying to call `toArray()` on the object:
`set.toArray is not a function` when it's really just expecting it to be a type ArgumentSet or SelectionSet.
What `generateArgumentList` is actually expecting is an `argumentSet`
Paired with: @delkopiso
=> Use fromQuery method to build argumentset for objects

addon/adapter.js, tests/integration/adapter-test.js
When trying to query records using string parameters, there is a chance the GraphQL query created will have some unescaped characters, causing a parsing error on the server side.
=> Avoid parsing error on the server side when querying

addon/serializer.js, package.json, tests/integration/serializer-test.js
Serializer is sending `undefined` in the graphql payload, which gets converted to `"undefined"` in the backend
This change should default to `null` when `undefined` is present
=> Converting regular attributes from 'undefined' to 'null'

addon/parser.js, package.json
When resolving an ember model object graph, objects that contain relationships that itself contain relationships with the same name do not get resolved.
Example:
```
+-- angle
+-- id
+-- title
+-- details
+-- angleTeamMemberships
|   +-- id
|   +-- name
|   +-- avatar
+-- geographies
|   +-- id
|   +-- name
|   +-- code
+-- angleCompanies
|   +-- id
|   +-- alphaCompany
|   |   +-- id
|   |   +-- name
|   +-- aliasCompany
|   |   +-- id
|   |   +-- name
+-- subAngles
+-- id
+-- title
+-- details
+-- angleTeamMemberships (missing)
|   +-- id
|   +-- name
|   +-- avatar
+-- geographies (missing)
|   +-- id
|   +-- name
|   +-- code
+-- angleCompanies (missing)
+-- id
+-- alphaCompany
|   +-- id
|   +-- name
+-- aliasCompany
+-- id
+-- name
```
Given the angle object graph above, a …
=> Allow explicit relationship resolution
